/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Experiments03LayoutRouteImport } from './routes/experiments/03-layout'
import { Route as Experiments02LayoutRouteImport } from './routes/experiments/02-layout'
import { Route as Experiments01LayoutRouteImport } from './routes/experiments/01-layout'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Experiments03LayoutRoute = Experiments03LayoutRouteImport.update({
  id: '/experiments/03-layout',
  path: '/experiments/03-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const Experiments02LayoutRoute = Experiments02LayoutRouteImport.update({
  id: '/experiments/02-layout',
  path: '/experiments/02-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const Experiments01LayoutRoute = Experiments01LayoutRouteImport.update({
  id: '/experiments/01-layout',
  path: '/experiments/01-layout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/experiments/01-layout': typeof Experiments01LayoutRoute
  '/experiments/02-layout': typeof Experiments02LayoutRoute
  '/experiments/03-layout': typeof Experiments03LayoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/experiments/01-layout': typeof Experiments01LayoutRoute
  '/experiments/02-layout': typeof Experiments02LayoutRoute
  '/experiments/03-layout': typeof Experiments03LayoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/experiments/01-layout': typeof Experiments01LayoutRoute
  '/experiments/02-layout': typeof Experiments02LayoutRoute
  '/experiments/03-layout': typeof Experiments03LayoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/experiments/01-layout'
    | '/experiments/02-layout'
    | '/experiments/03-layout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/experiments/01-layout'
    | '/experiments/02-layout'
    | '/experiments/03-layout'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/experiments/01-layout'
    | '/experiments/02-layout'
    | '/experiments/03-layout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  Experiments01LayoutRoute: typeof Experiments01LayoutRoute
  Experiments02LayoutRoute: typeof Experiments02LayoutRoute
  Experiments03LayoutRoute: typeof Experiments03LayoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/03-layout': {
      id: '/experiments/03-layout'
      path: '/experiments/03-layout'
      fullPath: '/experiments/03-layout'
      preLoaderRoute: typeof Experiments03LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/02-layout': {
      id: '/experiments/02-layout'
      path: '/experiments/02-layout'
      fullPath: '/experiments/02-layout'
      preLoaderRoute: typeof Experiments02LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/01-layout': {
      id: '/experiments/01-layout'
      path: '/experiments/01-layout'
      fullPath: '/experiments/01-layout'
      preLoaderRoute: typeof Experiments01LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  Experiments01LayoutRoute: Experiments01LayoutRoute,
  Experiments02LayoutRoute: Experiments02LayoutRoute,
  Experiments03LayoutRoute: Experiments03LayoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
